const data = {
  products: [
    {
      image: '/images/p1.jpg',
      name: 'Стелька orto',
      slug: 'stelka',
      category: 'стельки',
      articul: 'ae123hbj344j5h',
      size: '42',
      color: 'синий',
      length: '',
      price: 600,
      brand: 'ORTO',
      country: 'Германия',
      rating: 0,
      numReviews: 0,
      decription: 'Описание стельки',
    },
    {
      image: '/images/p2.jpg',
      name: 'Стелька correct',
      slug: 'stelka_correct',
      category: 'стельки',
      articul: 'ae123hbj344j5h',
      size: '42',
      color: 'бежевый',
      length: '',
      price: 600,
      brand: 'ORTO',
      country: 'Германия',
      rating: 0,
      numReviews: 0,
      decription: 'Описание стельки',
    },
    {
      image: '/images/p3.jpg',
      name: 'Подушка ОРТО',
      slug: 'podyshka',
      category: 'ортопедические подушки',
      articul: 'ae123hbj374j5h',
      size: '42',
      color: 'белый',
      length: '',
      price: 2200,
      brand: 'ORTO',
      country: 'Германия',
      rating: 0,
      numReviews: 0,
      decription: 'Описание подушки',
    },
    {
      image: '/images/p4.jpg', //679 x 829
      name: 'Гольфы женские',
      slug: 'golf',
      category: 'гольфы',
      articul: 'ae123hbd344j5h',
      size: '42',
      color: 'синий',
      length: '',
      price: 1200,
      brand: 'ORTO',
      country: 'Россия',
      rating: 0,
      numReviews: 0,
      decription: 'Описание гольфов',
    },
  ],
};

export default data;
